name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  coq:
    name: Coq proofs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Coq
        run: |
          sudo apt update
          sudo apt install -y opam m4 git
          opam init -y --bare
          opam switch create coq-8.19.0 ocaml-base-compiler.4.14.1
          eval $(opam env)
          opam install -y coq
      - name: Build Coq files
        run: |
          cd coq
          coqc fs_model.v
          coqc invariants.v
          coqc fix_bitmap.v

  rust:
    name: Rust validator
    runs-on: ubuntu-latest
    needs: coq
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Rust project
        run: |
          cd vrl_validator
          cargo build --release

      - name: Run Rust tests
        run: |
          cd vrl_validator
          cargo test --release
